# Generated by Django 6.0.4 on 2026-04-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_id',
        ),
    ]
